version: '3.8'
services:
# BANCO DADOS PROPOSTA--------------------------------------------------------
  banco-dados-proposta:
    image: mariadb:latest
    profiles:
      - producao
      - desenvolvimento
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=proposta
      - MYSQL_PASSWORD=proposta
      - MYSQL_DATABASE=proposta
    ports:
      - 3306:3306
    volumes:
      - banco-dados-proposta-volume:/var/lib/mariadb
    networks:
      - proposta-network
# ANALISE FINANCEIRA API
  analise-financeira:
    image: zupacademy/analise-financeira
    profiles:
      - producao
      - desenvolvimento
    ports:
      - 8081:8081
    environment:
      SERVER_PORT: 8081
      LOG_LEVEL: INFO
      URL_SISTEMA_CARTAO: http:/contas:8082/api/cartoes
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    networks:
      - proposta-network
# CONTAS API
  contas:
    image: zupacademy/contas
    profiles:
      - producao
      - desenvolvimento
    ports:
      - 8082:8082
    environment:
      SERVER_PORT: 8082
      LOG_LEVEL: INFO
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    networks:
      - proposta-network
# PROPOSTA API
  proposta:
    image: thiagohayacizup/proposta
    build: ..
    profiles:
      - producao
    ports:
      - 8080:8080
    depends_on:
      - banco-dados-proposta
      - analise-financeira
      - contas
    environment:
      DATABASE_HOST: banco-dados-proposta
      DATABASE: proposta
      DATABASE_PORT: 3306
      DATABASE_USER: proposta
      DATABASE_PASSWORD: proposta
      SOLICITACAO_ANALISE_FINANCEIRA: http://analise-financeira:8081
      CARTOES: http://contas:8082
      SCHEDULER_INITIAL_DELAY: 5000
      SCHEDULER_FIXED_DELAY: 10000
    networks:
      - proposta-network
# KEYCLOAK
  keycloak:
    image: jboss/keycloak:11.0.0
    profiles:
      - producao
      - desenvolvimento
    ports:
      - 8443:8443
      - 8083:8080
      - 9990:9990
    depends_on:
      - banco-dados-proposta
      - analise-financeira
      - contas
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: banco-dados-proposta
      DB_PORT: 3306
      DB_DATABASE: proposta
      DB_USER: proposta
      DB_PASSWORD: proposta
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_ISSUER_URI: http://keycloak:8083/auth/realms/proposta
      KEYCLOAK_JWKS_URI: http://keycloak:8083/auth/realms/proposta/protocol/openid-connect/certs
    restart: on-failure
    networks:
      - proposta-network
# PROMETHEUS
  prometheus:
    image: prom/prometheus:v2.22.0
    profiles:
      - producao
      - desenvolvimento
    volumes:
      - prometheus-volume:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - proposta-network
# GRAFANA
  grafana:
    image: grafana/grafana:7.3.4
    profiles:
      - producao
      - desenvolvimento
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - proposta-network

volumes:
  banco-dados-proposta-volume:
    name: banco-dados-proposta-volume
  grafana-volume:
    name: grafana-volume
  prometheus-volume:
    name: prometheus-volume

networks:
  proposta-network:
    driver: bridge