version: '3.5'
services:
# BANCO DADOS PROPOSTA--------------------------------------------------------
  banco-dados-proposta:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=proposta
      - MYSQL_PASSWORD=proposta
      - MYSQL_DATABASE=proposta
    ports:
      - 3306:3306
    volumes:
      - banco-dados-proposta-volume:/var/lib/mariadb
# ADMINER --------------------------------------------------------------------
  adminer:
    image: adminer:latest
    ports:
      - 8081:8080

volumes:
  banco-dados-proposta-volume:
    name: banco-dados-proposta-volume